name: urja_kisan
description: AI Crop Optimization App for Indian farmers
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.8.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # Networking
  http: ^1.1.1
  dio: ^5.0.0

  # Connectivity
  connectivity_plus: ^7.0.0

  # Speech / voice
  speech_to_text: ^7.3.0
  flutter_tts: ^3.6.3

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2   # match flutter_localizations requirement

  # Routing / utilities
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13  # needed for Hive code gen
  hive_generator: ^2.0.0 # needed for Hive code gen

flutter:
  generate: true         # <<< Important: enables gen-l10n
  uses-material-design: true

  assets:
    - assets/images/
